# this file goes in the user's ~/.prefect/ directory. The prefect client will look for this to point queries to.
# without this it will try to reach the prefect cloud, which isn't what I'm going for

backend = "server"

[server]

host = "http://prefect-ui.g-clef.net"
endpoint = "http://prefect-ui.g-clef.net:4200"
