apiVersion: v1
kind: ConfigMap
metadata:
  name: self-signed-ca-setup-script
  namespace: kube-system
data:
  setup.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/ca.crt && update-ca-certificates && systemctl restart containerd
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: self-signed-docker-ca
  labels:
    k8s-app: self-signed-docker-ca
spec:
  selector:
    matchLabels:
      k8s-app: self-signed-docker-ca
  template:
    metadata:
      labels:
        k8s-app: self-signed-docker-ca
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: init-node
        command: ["nsenter"]
        args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "$(SETUP_SCRIPT)"]
        image: debian
        env:
        - name: TRUSTED_CERT
          valueFrom:
            secretKeyRef:
              name: private-registry-ca
              key: registry-ca
        - name: SETUP_SCRIPT
          valueFrom:
            configMapKeyRef:
              name: self-signed-setup-script
              key: setup.sh
        securityContext:
          privileged: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1