apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: private-registry-ca
  namespace: kube-system
  labels:
    k8s-app: private-registry-ca
spec:
  selector:
    matchLabels:
      name: private-registry-ca
  template:
    metadata:
      labels:
        name: private-registry-ca
    spec:
      containers:
      - name: private-registry-ca
        securityContext:
          privileged: true
        image: debian
        command: [ 'nsenter' ]
        args:
            - --mount=/proc/1/ns/mnt
            - --
            - sh
            - -c
            - "cp /home/core/registry-ca /usr/local/share/ca-certificates/ca.crt && /usr/sbin/update-ca-certificates && systemctl restart containerd"
        volumeMounts:
        - name: etc-docker
          mountPath: /etc/docker/certs.d
        - name: ca-cert
          mountPath: /home/core
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etc-docker
        hostPath:
          path: /etc/docker/certs.d
      - name: ca-cert
        secret:
          secretName: private-registry-ca
