apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgresql
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
    - uid=1000
    - gid=1000
    - mysymlinks
    - nobrl
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: postgresql-pv
    volumeAttributes:
      source: "//192.168.1.197/postgres_storage"
    nodeStageSecretRef:
      name: prefect-smb-secrets
      namespace: analysis
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: postgresql-pv
  storageClassName: postgresql