kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: postgresql-pvc
      containers:
        - name: postgresql
          image: postgres:13.3
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: "3Gi"
            requests:
              memory: "2Gi"
          volumeMounts:
            - name: datadir
              mountPath: /pgdata
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: postgresql-postgres-password
            - name: PGDATA
              value: "/pgdata/data"
      imagePullSecrets:
        - name: registrycreds
      initContainers:
        - name: init
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          image: alpine
          command:
            - /bin/chown
            - -R
            - "1000:1000"
            - /pgdata/data
          volumeMounts:
            - mountPath: /pgdata
              name: datadir
---
apiVersion: v1
kind: Service
metadata:
  name: malwaretl-postgres
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432